/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ict_content_match_server_CONSTANTS_H
#define ict_content_match_server_CONSTANTS_H

#include "ict_content_match_server_types.h"

namespace ContentMatchService {

class ict_content_match_serverConstants {
 public:
  ict_content_match_serverConstants();

};

extern const ict_content_match_serverConstants g_ict_content_match_server_constants;

} // namespace

#endif

