all:	./src/ContentMatchTest.cpp 
	 g++ -o ContentMatch ./src/SentenceSplit.cpp  ./src/SentAndPosition.cpp ./src/ModifyResult.cpp ./src/CompareArticles.cpp ./src.ArticleAnalyze.cpp ./src/ContentMatchTest.cpp -I./include -L./lib -lICTTextMining -lpthread -pthread -L./usr/local/lib
clean:
	rm -f *.o 