/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ict_content_match_server_constants.h"

namespace ContentMatchService {

const ict_content_match_serverConstants g_ict_content_match_server_constants;

ict_content_match_serverConstants::ict_content_match_serverConstants() {
}

} // namespace

