all:	./src/WebSearchTest.cpp 
	 g++ -o WebSearch ./src/GetMeta.cpp  ./src/SimiCompare.cpp ./src/WebSearchTest.cpp -I./include -L./lib -lICTTextMining -lgetmeta -lpthread -lidn -lldap -lrt -ljson -pthread -L./usr/local/lib
clean:
	rm -f *.o 

